### ISSUE TITLE
reverse encoder

### ISSUE THREAD

**Issue by ledouxsm** [boourns/eurorack#1]
Hey would it be possible to create a separate .wav file for DIY modules with the reversed encoder?  I know the fix in the encoder.h file is simple, but I can't personally figure out how to recompile my changes into a new .wav to play into my DIY braids.

**Comment by boourns** [comment]
next firmware release will have a menu setting item for reverse encoder support.

**Comment by ledouxsm** [comment]
thank you so much!! you just saved one of my diy modules!  he other had the correct encoder :P

how should i stay in the loop for once it rolls out?

st. thomas ledoux

**Comment by boourns** [comment]
I'll close this issue when the next firmware is released, and I can comment too.  Cheers!

**Comment by TimoRozendal** [comment]
@ledouxsm as an intermediate you solution you can use this file:
[braids_rev_encoder.wav.zip](https://github.com/boourns/eurorack-renaissance/files/2044980/braids_rev_encoder.wav.zip)

@boourns I recompiled the code of the latest release with the encoder.h from Bees in the trees with the define #define BACKWARDS_ENCODER, I hope you don't mind it that I post that here

Thanks for your work @boourns !

**Comment by boourns** [comment]
No problem, I just can't guarantee the file but if you're comfortable using that go for it

**Comment by vicsol** [comment]
Thanks

**Comment by boourns** [comment]
Would either of you like to be beta testers for the next release of this firmware?  Let me know.  You'd need to have a Braids module (DIY is fine), JTAG adapter, and a few hours to spare.  Email me tom at burns dot ca

**Comment by ledouxsm** [comment]
i dont have a jtag adapter, but i do have time to spare

**Comment by boourns** [comment]
@ledouxsm I would suggest you not become a beta tester then.  I learnt recently there is a way that a bad firmware wav could brick a Braids module, so I want to ensure beta testers can flash themselves out of a bricking situation.  I know how to avoid that situation (flash size needs to be under 108k), but I want a few testers to also run the firmware update just to make sure we're safe before releasing to the public.

**Comment by ledouxsm** [comment]
also just to follow up, that reverse encoder file that @TimoRozendal uploaded seems to have worked!  looking forward to the next update.

**Comment by naturarum** [comment]
@boourns did you get my email? would love to help out beta testing Renaissance.

**Comment by ghost** [comment]
I have Braids, Rings, lots of time and a jtag if you still need any beta testers.

**Comment by boourns** [comment]
@brycecake (and anyone else who feels comfortable beta testing), thanks for your response!

I have a beta cut of Renaissance 0.4, you can download it here: https://burns.ca/eurorack-next.html

I'm hoping to release it publicly in the next couple weeks, please let me know how it goes if you get a chance to try it between now and then.

Thanks!

**Comment by boourns** [comment]
Renaissance 0.4 has been released with reverse encoder support, so closing this issue.
