### ISSUE TITLE
Feedback range differs from stock Clouds

### ISSUE THREAD

**Issue by ghost** [boourns/eurorack#4]
It seems the feedback range pot is scaled different from the stock/uburst types.  Anything above 10 o'clock becomes a mess where the stock control you have to go almost to the end to get to that point..

**Comment by boourns** [comment]
@altitude909 which firmware and mode were you using?  Was freeze enabled, or not?  What was the reverb setting?  Sorry I realize this was a long time ago but I'm looking at a bugfix release before the end of the year.

**Comment by ghost** [comment]
whatever stock clouds was in april.  I have both on the bench so I'll A/B them shortly

**Comment by boourns** [comment]
That would be excellent, with a video or audio demo would help a ton too if possible.

**Comment by boourns** [comment]
I'm currently testing with the "stock" firmware and I don't see any issue with feedback.  I believe the "parasites" firmware treats feedback a bit more extreme, possibly it adds the reverb as part of the feedback setting.

**Comment by ghost** [comment]
That very well be the case.  I normally ship with parasites, I assumed the stock functionality of clouds mode was left stock in the parasites but I did compare the parasites build monsoon to a stock clouds firmware. I'll confirm shortly

**Comment by boourns** [comment]
I don't fully understand the changes, but I can confirm that feedback calculation is different between Stock and Parasites firmwares.

Relevant code, stock firmware: https://github.com/boourns/eurorack/blob/master/clouds/dsp/granular_processor.cc#L188-L203
```
  // Apply feedback, with high-pass filtering to prevent build-ups at very
  // low frequencies (causing large DC swings).
  ONE_POLE(freeze_lp_, parameters_.freeze ? 1.0f : 0.0f, 0.0005f)
  float feedback = parameters_.feedback;
  float cutoff = (20.0f + 100.0f * feedback * feedback) / sample_rate();
  fb_filter_[0].set_f_q<FREQUENCY_FAST>(cutoff, 1.0f);
  fb_filter_[1].set(fb_filter_[0]);
  fb_filter_[0].Process<FILTER_MODE_HIGH_PASS>(&fb_[0].l, &fb_[0].l, size, 2);
  fb_filter_[1].Process<FILTER_MODE_HIGH_PASS>(&fb_[0].r, &fb_[0].r, size, 2);
  float fb_gain = feedback * (1.0f - freeze_lp_);
  for (size_t i = 0; i < size; ++i) {
    in_[i].l += fb_gain * (
        SoftLimit(fb_gain * 1.4f * fb_[i].l + in_[i].l) - in_[i].l);
    in_[i].r += fb_gain * (
        SoftLimit(fb_gain * 1.4f * fb_[i].r + in_[i].r) - in_[i].r);
  }
```

Relevant code, Parasites:
https://github.com/mqtthiqs/parasites/blob/master/clouds/dsp/granular_processor.cc#L315-L334

```
  // Apply feedback, with high-pass filtering to prevent build-ups at very
  // low frequencies (causing large DC swings).
  float feedback = parameters_.feedback;

  if (playback_mode_ != PLAYBACK_MODE_OLIVERB &&
      playback_mode_ != PLAYBACK_MODE_RESONESTOR) {
    ONE_POLE(freeze_lp_, parameters_.freeze ? 1.0f : 0.0f, 0.0005f)
    float cutoff = (20.0f + 100.0f * feedback * feedback) / sample_rate();
    fb_filter_[0].set_f_q<FREQUENCY_FAST>(cutoff, 0.75f);
    fb_filter_[1].set(fb_filter_[0]);
    fb_filter_[0].Process<FILTER_MODE_HIGH_PASS>(&fb_[0].l, &fb_[0].l, size, 2);
    fb_filter_[1].Process<FILTER_MODE_HIGH_PASS>(&fb_[0].r, &fb_[0].r, size, 2);
    float fb_gain = feedback * (2.0f - feedback) * (1.0f - freeze_lp_);
    for (size_t i = 0; i < size; ++i) {
      in_[i].l += fb_gain * (
                             SoftLimit(fb_gain * 1.4f * fb_[i].l + in_[i].l) - in_[i].l);
      in_[i].r += fb_gain * (
                             SoftLimit(fb_gain * 1.4f * fb_[i].r + in_[i].r) - in_[i].r);
    }
  }
```

From a first glance looks like the increased feedback is intentional, `    float fb_gain = feedback * (2.0f - feedback) * (1.0f - freeze_lp_);` on Parasites would be more extreme than  `  float fb_gain = feedback * (1.0f - freeze_lp_);`.

<img width="389" alt="image" src="https://user-images.githubusercontent.com/699550/103012665-ee4d5600-4509-11eb-91eb-9f34f3af538d.png">

**Comment by ghost** [comment]
ok. thats that then.  Thanks for looking into it

**Comment by boourns** [comment]
You're welcome!  I have a fix coming sometime this week that fixes the wet/dry CV range to reach from fully wet to fully dry.
